name: "Staging updater"
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * 1'

env:
  RUBY_VERSION: 2.6.5
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_HOST: localhost

jobs:
  check:
    name: Check if develop branch has changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0

      - name: Get local commit hash from Gemfile.lock
        run: "echo '::set-env name=LAST_LOCAL_COMMIT::'$(grep 'revision.*' Gemfile.lock | sed s/\\ \\ revision:\\ //)"

      - name: Get remote commit hash from repository
        run: "echo '::set-env name=LAST_REMOTE_COMMIT::'$(git ls-remote https://github.com/decidim/decidim refs/heads/develop | cut -f1)"

      - name: Show both hashes
        run: "echo 'Gemfile.lock:  ${{ env.LAST_LOCAL_COMMIT }}\ndeploy branch: ${{ env.LAST_REMOTE_COMMIT }}'"

      - name: Fail if both values are equal
        if: ${{ env.LAST_LOCAL_COMMIT == env.LAST_REMOTE_COMMIT }}
        run: exit 1

  main:
    name: Update decidim gem to develop branch
    needs: check
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2.0.0

      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install Ruby dependencies
        run: bundle install --path vendor/bundle --jobs 4

      - name: Update decidim gem
        run: bundle update --source decidim

      - name: Update database schema
        run: bundle exec rake db:create db:schema:load decidim:upgrade db:migrate

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update to the last version of decidim develop branch
