name: "Staging updater"
on:
  schedule:
    - cron:  '*/15 * * * *'

env:
  RUBY_VERSION: 2.6.6
  DEFAULT_BRANCH: develop
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_HOST: localhost
  PR_BODY: ""

jobs:
  check:
    name: Check if develop branch has changed
    steps:
      - uses: actions/checkout@v2.0.0

      - name: Get local commit hash from Gemfile.lock
        run: "echo '::set-env LAST_LOCAL_COMMIT=$(grep -O 'revision.*' Gemfile.lock | sed s/\ \ revision:\ //)'"

      - name: Get remote commit hash from repository
        run: "echo '::set-env LAST_REMOTE_COMMIT=$(git ls-remote https://github.com/decidim/decidim refs/heads/develop | cut -f1)"

      - name: Fail if both values are equal
        if: ${{ env.LAST_LOCAL_COMMIT == LAST_REMOTE_COMMIT }}
        run: exit 1

  main:
    name: Update decidim gem to develop branch
    needs: check
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2.0.0

      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install Ruby dependencies
        run: bundle install --path vendor/bundle --jobs 4

      - name: Update database schema
        run: bundle exec rake db:create db:schema:load decidim:upgrade db:migrate

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update to the last version of decidim develop branch


